network_type: glow
use_DFCData: true
use_Shadow: true
exp_dir: ./glow_train
wandb_offline: true
wandb_debug_mode: true
freq:
  step_epoch: 100
  save: 10000
  plot: 100
  test: 50000
optimizer: Adam
weight_decay: 0.0001
learning_rate: 0.001
lr_policy: step
lr_gamma: 0.5
lr_step_size: 40
lr_clip: 1.0e-05
momentum_original: 0.1
momentum_decay: 0.5
momentum_step_size: 20
momentum_min: 0.01
weight_init: xavier
total_epoch: 250
resume_epoch: -1
cuda_id: 0
num_workers: 4
batch_size: 8
model:
  joint_training: false
  network:
    type: pointnet
  flow:
    points: 22
    feature_dim: 1024
    hidden_dim: 64
    layer: 21
    block: 2
  sample_num: 8
  loss_weight:
    nll: 1.0
    cmap_loss: 1.0
dataset:
  root_path: data
  dataset_dir: DFCData
  hand_global_trans:
  - 0
  - -0.7
  - 0.2
  hand_global_rotation_xyz:
  - -1.57
  - 0
  - 3.14
  num_obj_points: 3000
  num_hand_points: 1024
  shadow_hand_mesh_dir: mjcf/meshes
  shadow_urdf_path: mjcf/shadow_hand.xml
  fps: false
device: cuda:0

